[build]
  command = "ng build --configuration=production"
  publish = "dist/AngKidsMart/browser"
  functions = "dist/AngKidsMart/server"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
